FROM node:boron

MAINTAINER Ivan Font <ifont@redhat.com>

# Create app directory and specify volume that will be bind mounted at runtime
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
VOLUME ["/usr/src/app"]

# Update mongo host from 'localhost' to 'mongo'
RUN sed -i 's/localhost/172.17.0.2/' router/config.js

# Expose port 8080
EXPOSE 8080

# Run container
CMD ["npm", "run", "dev"]
