#!/usr/bin/env bash
#
# updatedns - Run the updatedns.sh tool
#
#
#
set -o errexit
set -o nounset
set -o pipefail

SCRIPT_ROOT="$( cd "$( dirname "$(readlink -f "${BASH_SOURCE[0]}")" )" && pwd )"
${SCRIPT_ROOT}/updatedns.sh ${@} \
    -n pacman -z ${ZONE_NAME} -d ${DNS_NAME}
